[versions]
kilua = "0.0.31"
kotlin = "2.3.0"
compose = "1.11.0-alpha01"
kilua-rpc = "0.0.41"
ksp = "2.3.4"
kotlinx-datetime = "0.7.1"
ktor = "3.3.3"
logback = "1.5.23"
vite-kotlin = "0.8.0"
tailwindcss = "4.1.18"
arrow = "2.2.0"
mail = "1.5"
qr-code= "4.5.0"
html = "0.12.0"
google-api-client = "2.4.0"
jwt = "4.5.0"
bcrypt = "0.4"
koin = "4.1.1"

[libraries]
kilua = { module = "dev.kilua:kilua", version.ref = "kilua" }
kilua-common-types = { module = "dev.kilua:kilua-common-types", version.ref = "kilua" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

kilua-rpc = { module = "dev.kilua:kilua-rpc-ktor-koin", version.ref = "kilua-rpc" }
kilua-ssr = { module = "dev.kilua:kilua-ssr", version.ref = "kilua" }
kilua-ssr-server = { module = "dev.kilua:kilua-ssr-server-ktor", version.ref = "kilua" }

ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-contentNegotiation-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kilua-tailwindcss = { module = "dev.kilua:kilua-tailwindcss", version.ref = "kilua" }
kilua-bootstrap-icons = { module = "dev.kilua:kilua-bootstrap-icons", version.ref = "kilua" }
kilua-routing = { module = "dev.kilua:kilua-routing", version.ref = "kilua" }
kilua-tempus-dominus = { module = "dev.kilua:kilua-tempus-dominus", version.ref = "kilua" }
kilua-tom-select = { module = "dev.kilua:kilua-tom-select", version.ref = "kilua" }
kilua-imask = { module = "dev.kilua:kilua-imask", version.ref = "kilua" }
kilua-rsup-progress = { module = "dev.kilua:kilua-rsup-progress", version.ref = "kilua" }
kilua-animation = { module = "dev.kilua:kilua-animation", version.ref = "kilua" }
kilua-testutils = { module = "dev.kilua:kilua-testutils", version.ref = "kilua" }

arrow-stack = { module = "io.arrow-kt:arrow-stack", version.ref = "arrow" }
arrow-serialization = { module = "io.arrow-kt:arrow-core-serialization", version.ref = "arrow" }
arrow-core = { module = "io.arrow-kt:arrow-core" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-ktor = { module = "io.insert-koin:koin-ktor" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-test-junit = { module = "io.insert-koin:koin-test-junit4" }

mail = { module = "org.apache.commons:commons-email", version.ref = "mail" }
qrCode = { module = "io.github.g0dkar:qrcode-kotlin", version.ref = "qr-code" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "html" }
bcrypt = { module = "org.mindrot:jbcrypt", version.ref = "bcrypt" }
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "google-api-client" }
jwt = { module = "com.auth0:java-jwt", version.ref = "jwt" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kilua = { id = "dev.kilua", version.ref = "kilua" }
kilua-rpc = { id = "dev.kilua.rpc", version.ref = "kilua-rpc" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
vite-kotlin = { id = "dev.opensavvy.vite.kotlin", version.ref = "vite-kotlin" }
